# Generated by Django 3.0.6 on 2020-05-20 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burgerbuilder_api', '0002_userprofile_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('street', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=6)),
                ('deliveryMethod', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salad', models.PositiveIntegerField()),
                ('bacon', models.PositiveIntegerField()),
                ('cheese', models.PositiveIntegerField()),
                ('meat', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('contact_data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burgerbuilder_api.ContactData')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
