# Generated by Django 3.0.6 on 2020-05-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burgerbuilder_api', '0003_contactdata_ingredients_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdata',
            old_name='deliveryMethod',
            new_name='delivery_method',
        ),
        migrations.RenameField(
            model_name='contactdata',
            old_name='zipcode',
            new_name='zip_code',
        ),
    ]
